### ISSUE TITLE
Criar gerador do arquivo `.proto`

### ISSUE THREAD

**Issue by afmireski** [afmireski/proto-message-generator#5]
# Description
Será necessário criar duas funções:
1. A primeira receberá o `arquivo_de_entrada` e o converterá para um objeto `ProtoMessage`.
2. A segunda receberá o `objeto` gerado acima e o utilizará para montar a `message` no `arquivo_de_saida`

# Additional context

# Tasks
- [x] Criar função `generate_proto_message`.
- [x] Criar função `write_message`.
- [x] Atualizar `CHANGELOG.md`
