### ISSUE TITLE
Melhorar conversão de Arrays

### ISSUE THREAD

**Issue by afmireski** [afmireski/proto-message-generator#9]
# Description
Atualmente o reconhecimento de variáveis `arrays` já funciona, porém somente com aquelas que possuem sintaxe `var: type[]`. Variáveis com sintaxe `var: Array<T>` são entendidas como classes.  
O mesmo problema ocorre ao tentar identificar `enums`.

Assim se torna necessário alterar o código para reconhecer esses tipos de variáveis.

# Additional context
- _Os enums serão identificados pelas chaves `keyof typeof` e tipados no proto como `string`_

# Tasks
- [x] Alterar `message_variable.py` para reconhecer variáveis do tipo `var: Array<T>`;
- [x] Alterar `message_variable.py` para reconhecer variáveis do tipo `enum`;
- [x] Atualizar `CHANGELOG.md`
